### ISSUE TITLE
Title bar does not respect `prefers-reduced-motion: reduce`

### ISSUE THREAD

**Issue by maxnordlund** [Abdenasser/neohtop#109] opened 2024-11-12 23:16 UTC
**Describe the bug**
The title bar shouldn't be animated if the user (like me) has set prefers reduced motion in the system settings.

**To Reproduce**
1. Open the app
2. `NeoHtop` in the title bar blinks

**Expected behavior**
The title would not blink.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.7
 - Version 1.1.0 (20241110.180333)

**Additional context**
You can use [a `@media` query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) for it, so hopefully it's an easy fix.

I would argue that it shouldn't be animated at all, or at the very least be off by default ant configurable. I find it quite distracting, and while the animation is pretty neat, it loses its novelty pretty fast. Perhaps it can find a better home somewhere on the web page?

**Comment by Abdenasser** [comment] 2024-11-12 23:48
not a bug, since that's not the native os title bar.

**Comment by philsherry** [comment] 2024-12-03 08:59
I saw this was marked as completed, so I downloaded it to take a look but then I still see a flashing title bar logo.  

That tiny bar is best used for regular text, while custom images are more suited to the About screen where they can be much bigger. 

While I can very easily configure the processes to refresh at a much more sensible `5s` and longer, that only seems to highlight the title bar flashing even more (for me, anyway). I think OP was right to use the bug label, as it’s an accessibility bug. Any chance you might look into fixing it please?

**Comment by Abdenasser** [comment] 2024-12-03 10:00
@philsherry will try to find some time to work on a fix, would also appreciate it if someone can submit a PR.

**Closed** 2024-12-03 12:02 UTC
Labels: enhancement
